version: "3"
networks:
  my-lovely:
services:
  my-db:
    image: picae/fec-initial:ref-mysql2
    container_name: nb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
    ports:
      - "3300:3306"
    networks:
      my-lovely:
        aliases:
         - "nb-mysql-db"
    restart: unless-stopped
  app_db:
    image: picae/fec-initial:ref-app2-server-mod
    container_name: nb-app-server-mod2
    ports:
      - "3001:3001"
    environment:
      PORT: "3001"
# DB_HOST should match "aliases"
      DB_HOST: "nb-mysql-db"
      DB_USER: "root"
      DB_PASSWORD: "password"
      DB_DATABASE: "navbar"
      DB_PORT: "3306"
# do not put "/" at the end of URL or any port numbers
      MY_URL: "http://localhost"
    networks:
      - "my-lovely"
    expose:
      - "3001"
    depends_on:
      - "my-db"
    restart: unless-stopped
    command: ["npm", "start"]
